require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/DescribeClass:
  Enabled: false

Style/Documentation:
  Enabled: false

